POST http://localhost:8000/products
Content-Type: application/json

{
    "name": "Meu Produto 3",
    "price": 420
}

###

GET http://localhost:8000/products/fde04d59-ffb0-48c5-88e9-229a29194fe2 HTTP/1.1
Content-Type: application/json

###
GET http://localhost:8000/products/page=1&limit=10&sort=asc HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzUzMDk0NTAsInN1YiI6IjlmM2MxNjBiLTY2NjYtNGFiMC1hNjdmLWE2MmFlZmM4YjJkNCJ9.R7GCooNE1tXFI5NT-H_-M1XhaXB5OKcaZqG6hpdvmKE

###

PUT http://localhost:8000/products/fde04d59-ffb0-48c5-88e9-229a29194fe2 HTTP/1.1
Content-Type: application/json

{
    "name": "Meu Produto 3 Atualizado",
    "price": 530.69
}

###

DELETE http://localhost:8000/products/fde04d59-ffb0-48c5-88e9-229a29194fe2 HTTP/1.1
Content-Type: application/json