services:
  mysql:
    image: mysql/mysql-server:latest
    container_name: mysql
    restart: always
    platform: linux/amd64
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: goexpert
      MYSQL_PASSWORD: vieira
      MYSQL_USER: rafael
    ports:
      - "3306:3306"